services:
  db:
    container_name: banking-postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: moundirb
      POSTGRES_PASSWORD: password  # Added password
      POSTGRES_DB: banking_db  # Add this to create the database

      PGDATA: /data/postgres
    volumes:
        - db:/data/postgres
    ports:
      - "5332:5432"

    restart: unless-stopped


volumes:
    db: